# Generated by Django 4.0.4 on 2022-05-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_recipe_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
