# Generated by Django 4.0.4 on 2022-06-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='cover',
        ),
    ]
